EPAM+Alexey_Malashenko@EPBYMINW5875 MINGW64 ~/PycharmProjects/coursePythonFoundation/session_3/local_folder (develop)
$ git push
To https://github.com/alexey-malashenko/python_foundation.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://github.com/alexey-malashenko/python_foundation.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

EPAM+Alexey_Malashenko@EPBYMINW5875 MINGW64 ~/PycharmProjects/coursePythonFoundation/session_3/local_folder (develop)
$ git fetch
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 1), reused 3 (delta 1), pack-reused 0
Unpacking objects: 100% (3/3), 246 bytes | 7.00 KiB/s, done.
From https://github.com/alexey-malashenko/python_foundation
   1afe76b..77ce0b3  develop    -> origin/develop

EPAM+Alexey_Malashenko@EPBYMINW5875 MINGW64 ~/PycharmProjects/coursePythonFoundation/session_3/local_folder (develop)
$ git status
On branch develop
Your branch and 'origin/develop' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean

EPAM+Alexey_Malashenko@EPBYMINW5875 MINGW64 ~/PycharmProjects/coursePythonFoundation/session_3/local_folder (develop)
$ git pull
Auto-merging text_file.txt
CONFLICT (content): Merge conflict in text_file.txt
Automatic merge failed; fix conflicts and then commit the result.

EPAM+Alexey_Malashenko@EPBYMINW5875 MINGW64 ~/PycharmProjects/coursePythonFoundation/session_3/local_folder (develop|MERGING)
$ git status
On branch develop
Your branch and 'origin/develop' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Unmerged paths:
  (use "git add <file>..." to mark resolution)
        both modified:   text_file.txt

no changes added to commit (use "git add" and/or "git commit -a")

EPAM+Alexey_Malashenko@EPBYMINW5875 MINGW64 ~/PycharmProjects/coursePythonFoundation/session_3/local_folder (develop|MERGING)
$ ^C

EPAM+Alexey_Malashenko@EPBYMINW5875 MINGW64 ~/PycharmProjects/coursePythonFoundation/session_3/local_folder (develop|MERGING)
$ git commit -m "conflict"
error: Committing is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
U       text_file.txt

EPAM+Alexey_Malashenko@EPBYMINW5875 MINGW64 ~/PycharmProjects/coursePythonFoundation/session_3/local_folder (develop|MERGING)
$ git add .

EPAM+Alexey_Malashenko@EPBYMINW5875 MINGW64 ~/PycharmProjects/coursePythonFoundation/session_3/local_folder (develop|MERGING)
$ git commit -m "conflict"
[develop cd734f2] conflict

EPAM+Alexey_Malashenko@EPBYMINW5875 MINGW64 ~/PycharmProjects/coursePythonFoundation/session_3/local_folder (develop)
$ git push
Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (6/6), 539 bytes | 539.00 KiB/s, done.
Total 6 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 1 local object.
To https://github.com/alexey-malashenko/python_foundation.git
   77ce0b3..cd734f2  develop -> develop

EPAM+Alexey_Malashenko@EPBYMINW5875 MINGW64 ~/PycharmProjects/coursePythonFoundation/session_3/local_folder (develop)
$
S